class EmojiOption {
  const EmojiOption(this.emoji, this.label);

  final String emoji;
  final String label;
}

const List<EmojiOption> emojiOptionsCatalog = <EmojiOption>[
  EmojiOption('\u2728', 'Magic'),
  EmojiOption('\u2B50', 'Star'),
  EmojiOption('\uD83C\uDF1F', 'Glowing Star'),
  EmojiOption('\uD83D\uDCAB', 'Dizzy'),
  EmojiOption('\uD83D\uDD25', 'Fire'),
  EmojiOption('\uD83D\uDCA7', 'Water'),
  EmojiOption('\uD83C\uDF0A', 'Wave'),
  EmojiOption('\uD83C\uDF31', 'Nature'),
  EmojiOption('\uD83C\uDF32', 'Tree'),
  EmojiOption('\uD83C\uDF38', 'Blossom'),
  EmojiOption('\uD83C\uDF39', 'Rose'),
  EmojiOption('\uD83C\uDF3A', 'Hibiscus'),
  EmojiOption('\uD83C\uDF3B', 'Sunflower'),
  EmojiOption('\uD83C\uDF40', 'Clover'),
  EmojiOption('\u26A1', 'Electric'),
  EmojiOption('\u2744\uFE0F', 'Snow'),
  EmojiOption('\u2601\uFE0F', 'Cloud'),
  EmojiOption('\uD83C\uDF08', 'Rainbow'),
  EmojiOption('\uD83C\uDF19', 'Moon'),
  EmojiOption('\u2600\uFE0F', 'Sun'),
  EmojiOption('\uD83C\uDF0D', 'Earth'),
  EmojiOption('\uD83C\uDF10', 'Globe'),
  EmojiOption('\uD83D\uDC8E', 'Gem'),
  EmojiOption('\uD83D\uDC96', 'Sparkle Heart'),
  EmojiOption('\uD83D\uDC99', 'Blue Heart'),
  EmojiOption('\uD83D\uDC9A', 'Green Heart'),
  EmojiOption('\uD83D\uDC9B', 'Yellow Heart'),
  EmojiOption('\uD83D\uDC9C', 'Purple Heart'),
  EmojiOption('\uD83D\uDDA4', 'Black Heart'),
  EmojiOption('\uD83D\uDD11', 'Key'),
  EmojiOption('\uD83D\uDD12', 'Lock'),
  EmojiOption('\uD83D\uDD13', 'Unlock'),
  EmojiOption('\uD83D\uDCE1', 'Signal'),
  EmojiOption('\uD83D\uDCF6', 'Network'),
  EmojiOption('\uD83D\uDCBB', 'Laptop'),
  EmojiOption('\uD83D\uDDA5\uFE0F', 'Desktop'),
  EmojiOption('\u2328\uFE0F', 'Keyboard'),
  EmojiOption('\uD83D\uDDA8\uFE0F', 'Printer'),
  EmojiOption('\uD83D\uDCBE', 'Disk'),
  EmojiOption('\uD83D\uDCE6', 'Package'),
  EmojiOption('\uD83D\uDCEB', 'Mailbox'),
  EmojiOption('\uD83D\uDCEC', 'Inbox'),
  EmojiOption('\uD83D\uDCE8', 'Mail'),
  EmojiOption('\uD83D\uDCCC', 'Pin'),
  EmojiOption('\uD83D\uDD0D', 'Search'),
  EmojiOption('\uD83D\uDCA1', 'Idea'),
  EmojiOption('\uD83D\uDD26', 'Flashlight'),
  EmojiOption('\uD83C\uDFAE', 'Game'),
  EmojiOption('\uD83D\uDD79\uFE0F', 'Joystick'),
  EmojiOption('\uD83C\uDFC6', 'Trophy'),
  EmojiOption('\uD83C\uDFC5', 'Medal'),
  EmojiOption('\uD83C\uDFAF', 'Target'),
  EmojiOption('\uD83C\uDFB2', 'Dice'),
  EmojiOption('\uD83C\uDCCF', 'Card'),
  EmojiOption('\u265F\uFE0F', 'Chess'),
  EmojiOption('\uD83C\uDFA8', 'Art'),
  EmojiOption('\uD83C\uDFB5', 'Music'),
  EmojiOption('\uD83C\uDFA7', 'Headphones'),
  EmojiOption('\uD83C\uDFAC', 'Movie'),
  EmojiOption('\uD83D\uDCF7', 'Camera'),
  EmojiOption('\uD83D\uDCD6', 'Book'),
  EmojiOption('\uD83D\uDCDD', 'Note'),
  EmojiOption('\u270F\uFE0F', 'Pencil'),
  EmojiOption('\uD83D\uDEE1\uFE0F', 'Shield'),
  EmojiOption('\u2694\uFE0F', 'Swords'),
  EmojiOption('\uD83D\uDDE1\uFE0F', 'Dagger'),
  EmojiOption('\uD83C\uDFF9', 'Bow'),
  EmojiOption('\uD83E\uDDEA', 'Potion'),
  EmojiOption('\uD83E\uDDEC', 'DNA'),
  EmojiOption('\u2697\uFE0F', 'Alchemy'),
  EmojiOption('\uD83D\uDD2C', 'Microscope'),
  EmojiOption('\uD83D\uDD2D', 'Telescope'),
  EmojiOption('\uD83D\uDC7E', 'Alien'),
  EmojiOption('\uD83E\uDD16', 'Robot'),
  EmojiOption('\uD83D\uDC7B', 'Ghost'),
  EmojiOption('\uD83D\uDC80', 'Skull'),
  EmojiOption('\uD83D\uDC09', 'Dragon'),
  EmojiOption('\uD83E\uDD84', 'Unicorn'),
  EmojiOption('\uD83D\uDE80', 'Rocket'),
  EmojiOption('\uD83D\uDEF8', 'UFO'),
  EmojiOption('\uD83D\uDEE9\uFE0F', 'Plane'),
  EmojiOption('\uD83D\uDE97', 'Car'),
  EmojiOption('\uD83C\uDFCD\uFE0F', 'Motorcycle'),
  EmojiOption('\uD83D\uDEB2', 'Bike'),
  EmojiOption('\u2693', 'Anchor'),
  EmojiOption('\uD83D\uDCCD', 'Location'),
  EmojiOption('\uD83D\uDDFA\uFE0F', 'Map'),
  EmojiOption('\uD83D\uDDBC\uFE0F', 'Picture'),
  EmojiOption('\uD83C\uDFAD', 'Mask'),
  EmojiOption('\uD83C\uDFAA', 'Circus'),
  EmojiOption('\uD83C\uDF81', 'Gift'),
  EmojiOption('\uD83C\uDF88', 'Balloon'),
  EmojiOption('\uD83C\uDF89', 'Party'),
  EmojiOption('\uD83C\uDF83', 'Pumpkin'),
  EmojiOption('\u2615', 'Coffee'),
  EmojiOption('\uD83C\uDF75', 'Tea'),
  EmojiOption('\uD83C\uDF7A', 'Beer'),
  EmojiOption('\uD83C\uDF55', 'Pizza'),
  EmojiOption('\uD83C\uDF54', 'Burger'),
  EmojiOption('\uD83C\uDF5C', 'Ramen'),
  EmojiOption('\uD83C\uDF63', 'Sushi'),
  EmojiOption('\uD83C\uDF66', 'Ice Cream'),
  EmojiOption('\uD83D\uDC31', 'Cat'),
  EmojiOption('\uD83D\uDC36', 'Dog'),
  EmojiOption('\uD83D\uDC3A', 'Wolf'),
  EmojiOption('\uD83E\uDD8A', 'Fox'),
  EmojiOption('\uD83D\uDC3B', 'Bear'),
  EmojiOption('\uD83D\uDC30', 'Rabbit'),
  EmojiOption('\uD83D\uDC3C', 'Panda'),
  EmojiOption('\uD83D\uDC27', 'Penguin'),
  EmojiOption('\uD83E\uDD89', 'Owl'),
  EmojiOption('\uD83E\uDD8B', 'Butterfly'),
  EmojiOption('\uD83D\uDC1D', 'Bee'),
  EmojiOption('\uD83D\uDC1F', 'Fish'),
  EmojiOption('\uD83D\uDC19', 'Octopus'),
  EmojiOption('\uD83D\uDC33', 'Whale'),
  EmojiOption('\uD83D\uDE00', 'Smile'),
  EmojiOption('\uD83D\uDE04', 'Grin'),
  EmojiOption('\uD83D\uDE0E', 'Cool'),
  EmojiOption('\uD83E\uDD13', 'Nerd'),
  EmojiOption('\uD83E\uDD2F', 'Mind Blown'),
  EmojiOption('\uD83E\uDEE1', 'Salute'),
  EmojiOption('\uD83D\uDE08', 'Imp'),
  EmojiOption('\uD83D\uDC7F', 'Oni'),
  EmojiOption('\uD83E\uDD77', 'Ninja'),
  EmojiOption('\uD83D\uDC4D', 'Thumbs Up'),
  EmojiOption('\u270C\uFE0F', 'Victory'),
  EmojiOption('\uD83E\uDD18', 'Rock'),
  EmojiOption('\uD83E\uDD1F', 'Love You'),
  EmojiOption('\uD83D\uDC4F', 'Clap'),
  EmojiOption('\uD83D\uDCAA', 'Power'),
  EmojiOption('\uD83D\uDE4C', 'Raise Hands'),
  EmojiOption('\uD83E\uDD1D', 'Handshake'),
  EmojiOption('\uD83D\uDC41\uFE0F', 'Eye'),
  EmojiOption('\uD83D\uDC40', 'Eyes'),
  EmojiOption('\uD83E\uDDE0', 'Brain'),
  EmojiOption('\uD83E\uDEC0', 'Anatomical Heart'),
  EmojiOption('\uD83E\uDDBE', 'Mechanical Arm'),
  EmojiOption('\uD83D\uDC51', 'Crown'),
  EmojiOption('\uD83C\uDFA9', 'Hat'),
  EmojiOption('\uD83D\uDC8D', 'Ring'),
  EmojiOption('\uD83D\uDCB0', 'Money Bag'),
  EmojiOption('\uD83D\uDCB3', 'Card Payment'),
  EmojiOption('\uD83E\uDDF2', 'Magnet'),
  EmojiOption('\uD83E\uDDF0', 'Toolbox'),
  EmojiOption('\uD83D\uDEE0\uFE0F', 'Tools'),
  EmojiOption('\u2699\uFE0F', 'Gear'),
  EmojiOption('\uD83D\uDD27', 'Wrench'),
  EmojiOption('\uD83D\uDD29', 'Bolt'),
  EmojiOption('\uD83E\uDDF1', 'Brick'),
  EmojiOption('\uD83D\uDCA3', 'Bomb'),
  EmojiOption('\uD83E\uDDA0', 'Microbe'),
  EmojiOption('\uD83E\uDEAB', 'X Ray'),
  EmojiOption('\uD83E\uDE9B', 'Screwdriver'),
  EmojiOption('\uD83D\uDCE0', 'Fax'),
  EmojiOption('\uD83D\uDCDE', 'Phone'),
  EmojiOption('\uD83D\uDCF1', 'Mobile'),
  EmojiOption('\uD83D\uDD0B', 'Battery'),
  EmojiOption('\uD83D\uDD0C', 'Plug'),
  EmojiOption('\uD83D\uDCE2', 'Megaphone'),
  EmojiOption('\uD83D\uDCC0', 'DVD'),
  EmojiOption('\uD83D\uDCC1', 'Folder'),
  EmojiOption('\uD83D\uDCC2', 'Open Folder'),
  EmojiOption('\uD83D\uDDC3\uFE0F', 'Card Box'),
  EmojiOption('\uD83D\uDDC4\uFE0F', 'File Cabinet'),
  EmojiOption('\uD83D\uDCCA', 'Chart'),
  EmojiOption('\uD83D\uDCC8', 'Growth'),
  EmojiOption('\uD83D\uDCC9', 'Down Chart'),
  EmojiOption('\uD83D\uDD22', 'Numbers'),
  EmojiOption('\uD83D\uDD23', 'Symbols'),
  EmojiOption('\u2705', 'Check'),
  EmojiOption('\u274C', 'Cross'),
  EmojiOption('\u26A0\uFE0F', 'Warning'),
  EmojiOption('\u2753', 'Question'),
  EmojiOption('\u2757', 'Exclamation'),
  EmojiOption('\u267B\uFE0F', 'Recycle'),
  EmojiOption('\uD83D\uDD00', 'Shuffle'),
  EmojiOption('\uD83D\uDD01', 'Repeat'),
  EmojiOption('\u25B6\uFE0F', 'Play'),
  EmojiOption('\u23F8\uFE0F', 'Pause'),
  EmojiOption('\u23F9\uFE0F', 'Stop'),
  EmojiOption('\u23FA\uFE0F', 'Record'),
  EmojiOption('\uD83D\uDD34', 'Red Circle'),
  EmojiOption('\uD83D\uDFE0', 'Orange Circle'),
  EmojiOption('\uD83D\uDFE1', 'Yellow Circle'),
  EmojiOption('\uD83D\uDFE2', 'Green Circle'),
  EmojiOption('\uD83D\uDD35', 'Blue Circle'),
  EmojiOption('\uD83D\uDFE3', 'Purple Circle'),
  EmojiOption('\u2B1B', 'Black Square'),
  EmojiOption('\u2B1C', 'White Square'),
  EmojiOption('\uD83D\uDFE5', 'Red Square'),
  EmojiOption('\uD83D\uDFE6', 'Blue Square'),
  EmojiOption('\uD83D\uDFE7', 'Orange Square'),
  EmojiOption('\uD83D\uDFE8', 'Yellow Square'),
  EmojiOption('\uD83D\uDFE9', 'Green Square'),
  EmojiOption('\uD83D\uDFEA', 'Purple Square'),
  EmojiOption('\uD83D\uDD36', 'Diamond'),
  EmojiOption('\uD83D\uDD37', 'Blue Diamond'),
  EmojiOption('\uD83D\uDD38', 'Small Diamond'),
  EmojiOption('\uD83D\uDD39', 'Small Blue Diamond'),
  EmojiOption('\uD83C\uDF0C', 'Milky Way'),
  EmojiOption('\uD83E\uDE90', 'Planet'),
  EmojiOption('\u2604\uFE0F', 'Comet'),
  EmojiOption('\uD83C\uDF20', 'Shooting Star'),
  EmojiOption('\uD83D\uDCAF', 'Hundred'),
  EmojiOption('\uD83D\uDCA5', 'Impact'),
  EmojiOption('\uD83D\uDCA6', 'Splash'),
  EmojiOption('\uD83D\uDCA8', 'Dash'),
  EmojiOption('\uD83D\uDD73\uFE0F', 'Hole'),
  EmojiOption('\uD83D\uDD76\uFE0F', 'Sunglasses'),
  EmojiOption('\uD83E\uDDE9', 'Puzzle'),
  EmojiOption('\uD83E\uDE84', 'Magic Wand'),
  EmojiOption('\uD83D\uDEA9', 'Flag'),
  EmojiOption('\uD83C\uDFC1', 'Finish Flag'),
  EmojiOption('\uD83C\uDF70', 'Cake'),
  EmojiOption('\uD83C\uDF6A', 'Cookie'),
  EmojiOption('\uD83C\uDF6B', 'Chocolate'),
  EmojiOption('\uD83C\uDF6D', 'Lollipop'),
  EmojiOption('\uD83C\uDF4E', 'Apple'),
  EmojiOption('\uD83C\uDF4A', 'Orange'),
  EmojiOption('\uD83C\uDF4B', 'Lemon'),
  EmojiOption('\uD83C\uDF4C', 'Banana'),
  EmojiOption('\uD83C\uDF49', 'Watermelon'),
  EmojiOption('\uD83C\uDF47', 'Grapes'),
  EmojiOption('\uD83C\uDF53', 'Strawberry'),
  EmojiOption('\uD83C\uDF52', 'Cherries'),
  EmojiOption('\uD83C\uDF51', 'Peach'),
  EmojiOption('\uD83C\uDF4D', 'Pineapple'),
  EmojiOption('\uD83C\uDF45', 'Tomato'),
  EmojiOption('\uD83C\uDF46', 'Eggplant'),
  EmojiOption('\uD83C\uDF3D', 'Corn'),
  EmojiOption('\uD83C\uDF44', 'Mushroom'),
  EmojiOption('\uD83C\uDF5E', 'Bread'),
  EmojiOption('\uD83C\uDF57', 'Meat'),
  EmojiOption('\uD83C\uDF5F', 'Fries'),
  EmojiOption('\uD83C\uDF5D', 'Spaghetti'),
  EmojiOption('\uD83C\uDF5B', 'Curry'),
  EmojiOption('\uD83C\uDF59', 'Rice Ball'),
  EmojiOption('\uD83C\uDF5A', 'Rice'),
  EmojiOption('\uD83C\uDF61', 'Dango'),
  EmojiOption('\uD83C\uDF62', 'Oden'),
  EmojiOption('\uD83C\uDF7F', 'Popcorn'),
  EmojiOption('\uD83D\uDC2D', 'Mouse'),
  EmojiOption('\uD83D\uDC39', 'Hamster'),
  EmojiOption('\uD83D\uDC2F', 'Tiger'),
  EmojiOption('\uD83E\uDD81', 'Lion'),
  EmojiOption('\uD83D\uDC2E', 'Cow'),
  EmojiOption('\uD83D\uDC37', 'Pig'),
  EmojiOption('\uD83D\uDC38', 'Frog'),
  EmojiOption('\uD83D\uDC35', 'Monkey'),
  EmojiOption('\uD83D\uDC14', 'Chicken'),
  EmojiOption('\uD83D\uDC24', 'Chick'),
  EmojiOption('\uD83D\uDC26', 'Bird'),
  EmojiOption('\uD83D\uDC34', 'Horse'),
  EmojiOption('\uD83D\uDC11', 'Sheep'),
  EmojiOption('\uD83D\uDC18', 'Elephant'),
  EmojiOption('\uD83D\uDC22', 'Turtle'),
  EmojiOption('\uD83D\uDC0D', 'Snake'),
  EmojiOption('\uD83D\uDC0C', 'Snail'),
  EmojiOption('\uD83D\uDC1B', 'Bug'),
  EmojiOption('\uD83D\uDC1C', 'Ant'),
  EmojiOption('\uD83D\uDC1E', 'Ladybug'),
  EmojiOption('\uD83D\uDE42', 'Slight Smile'),
  EmojiOption('\uD83D\uDE09', 'Wink'),
  EmojiOption('\uD83D\uDE0A', 'Happy'),
  EmojiOption('\uD83D\uDE0D', 'Heart Eyes'),
  EmojiOption('\uD83D\uDE18', 'Kiss'),
  EmojiOption('\uD83D\uDE1C', 'Wink Tongue'),
  EmojiOption('\uD83D\uDE2D', 'Cry'),
  EmojiOption('\uD83D\uDE31', 'Scream'),
  EmojiOption('\uD83D\uDE34', 'Sleep'),
  EmojiOption('\uD83D\uDE37', 'Mask'),
  EmojiOption('\uD83D\uDE4F', 'Pray'),
  EmojiOption('\uD83D\uDC4C', 'OK'),
  EmojiOption('\uD83D\uDC46', 'Up'),
  EmojiOption('\uD83D\uDC47', 'Down'),
  EmojiOption('\uD83D\uDC48', 'Left'),
  EmojiOption('\uD83D\uDC49', 'Right'),
  EmojiOption('\uD83D\uDC5F', 'Shoe'),
  EmojiOption('\uD83D\uDC55', 'Shirt'),
  EmojiOption('\uD83D\uDC57', 'Dress'),
  EmojiOption('\uD83D\uDC5C', 'Bag'),
  EmojiOption('\uD83D\uDC53', 'Glasses'),
  EmojiOption('\uD83C\uDF02', 'Umbrella'),
  EmojiOption('\uD83D\uDC8A', 'Pill'),
  EmojiOption('\uD83D\uDC89', 'Syringe'),
  EmojiOption('\uD83D\uDEAA', 'Door'),
  EmojiOption('\uD83D\uDEBF', 'Shower'),
  EmojiOption('\uD83D\uDEBD', 'Toilet'),
  EmojiOption('\uD83D\uDEE2\uFE0F', 'Oil'),
  EmojiOption('\u26FD', 'Fuel'),
  EmojiOption('\uD83D\uDEA6', 'Traffic Light'),
  EmojiOption('\uD83D\uDEA7', 'Construction'),
  EmojiOption('\uD83D\uDE8F', 'Bus Stop'),
  EmojiOption('\uD83C\uDFAB', 'Ticket'),
  EmojiOption('\uD83C\uDF9F\uFE0F', 'Admission'),
  EmojiOption('\uD83C\uDF81', 'Present'),
  EmojiOption('\uD83C\uDF80', 'Ribbon'),
  EmojiOption('\uD83E\uDD8C', 'Deer'),
  EmojiOption('\uD83E\uDD8F', 'Rhinoceros'),
  EmojiOption('\uD83E\uDD9B', 'Hippopotamus'),
  EmojiOption('\uD83E\uDD92', 'Giraffe'),
  EmojiOption('\uD83E\uDD93', 'Zebra'),
  EmojiOption('\uD83E\uDD98', 'Kangaroo'),
  EmojiOption('\uD83E\uDD99', 'Llama'),
  EmojiOption('\uD83E\uDDA5', 'Sloth'),
  EmojiOption('\uD83E\uDDA6', 'Otter'),
  EmojiOption('\uD83E\uDDA8', 'Skunk'),
  EmojiOption('\uD83E\uDDA1', 'Badger'),
  EmojiOption('\uD83E\uDDAB', 'Beaver'),
  EmojiOption('\uD83E\uDDAD', 'Seal'),
  EmojiOption('\uD83E\uDD8D', 'Gorilla'),
  EmojiOption('\uD83E\uDDA7', 'Orangutan'),
  EmojiOption('\uD83E\uDD8E', 'Lizard'),
  EmojiOption('\uD83E\uDD96', 'T-Rex'),
  EmojiOption('\uD83E\uDD95', 'Sauropod'),
  EmojiOption('\uD83E\uDD88', 'Shark'),
  EmojiOption('\uD83D\uDC0A', 'Crocodile'),
  EmojiOption('\uD83D\uDC0B', 'Whale Side'),
  EmojiOption('\uD83D\uDC2C', 'Dolphin'),
  EmojiOption('\uD83E\uDD90', 'Shrimp'),
  EmojiOption('\uD83E\uDD91', 'Squid'),
  EmojiOption('\uD83E\uDD9E', 'Lobster'),
  EmojiOption('\uD83E\uDD80', 'Crab'),
  EmojiOption('\uD83E\uDD9A', 'Peacock'),
  EmojiOption('\uD83E\uDD9C', 'Parrot'),
  EmojiOption('\uD83E\uDDA2', 'Swan'),
  EmojiOption('\uD83E\uDD86', 'Duck'),
  EmojiOption('\uD83E\uDD85', 'Eagle'),
  EmojiOption('\uD83E\uDD87', 'Bat'),
  EmojiOption('\uD83E\uDD83', 'Turkey'),
  EmojiOption('\uD83D\uDC13', 'Rooster'),
  EmojiOption('\uD83D\uDC23', 'Hatching Chick'),
  EmojiOption('\uD83D\uDC25', 'Front Chick'),
  EmojiOption('\uD83E\uDD9D', 'Raccoon'),
  EmojiOption('\uD83E\uDD94', 'Hedgehog'),
  EmojiOption('\uD83D\uDC3F\uFE0F', 'Chipmunk'),
  EmojiOption('\uD83D\uDC07', 'Rabbit Body'),
  EmojiOption('\uD83D\uDC08', 'Cat Body'),
  EmojiOption('\uD83D\uDC15', 'Dog Body'),
  EmojiOption('\uD83D\uDC16', 'Pig Body'),
  EmojiOption('\uD83D\uDC04', 'Cow Body'),
  EmojiOption('\uD83D\uDC02', 'Ox'),
  EmojiOption('\uD83D\uDC03', 'Buffalo'),
  EmojiOption('\uD83D\uDC17', 'Boar'),
  EmojiOption('\uD83D\uDC2B', 'Camel'),
  EmojiOption('\uD83D\uDC2A', 'Two Hump Camel'),
  EmojiOption('\uD83D\uDC0E', 'Horse Body'),
  EmojiOption('\uD83D\uDC10', 'Goat'),
  EmojiOption('\uD83D\uDC0F', 'Ram'),
  EmojiOption('\uD83D\uDC12', 'Monkey Body'),
  EmojiOption('\uD83D\uDC06', 'Leopard'),
  EmojiOption('\uD83D\uDC05', 'Tiger Body'),
  EmojiOption('\uD83D\uDC29', 'Poodle'),
  EmojiOption('\uD83D\uDC3E', 'Paw Prints'),
];
String emojiNameFor(String emoji) {
  for (final EmojiOption option in emojiOptionsCatalog) {
    if (option.emoji == emoji) {
      return option.label;
    }
  }
  return 'Emoji';
}

String emojiLabelForValue(String value) {
  final List<String> emojis = selectedEmojiValuesFromCatalog(value);
  final List<String> labels = emojis
      .map((String emoji) => '$emoji ${emojiNameFor(emoji)}')
      .toList(growable: false);
  if (labels.isEmpty) {
    return 'Emoji';
  }
  return labels.join('  ');
}

List<String> selectedEmojiValuesFromCatalog(String value) {
  final List<String> selected = <String>[];
  int index = 0;
  while (index < value.length && selected.length < 3) {
    EmojiOption? match;
    for (final EmojiOption option in emojiOptionsCatalog) {
      if (value.startsWith(option.emoji, index) &&
          (match == null || option.emoji.length > match.emoji.length)) {
        match = option;
      }
    }
    if (match == null) {
      index += 1;
      continue;
    }
    selected.add(match.emoji);
    index += match.emoji.length;
  }
  return selected;
}
