import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outputDir = join(scriptDir, "fixtures");
const generatedAt = "2026-01-01T00:00:00.000Z";
const SQL_INSERT_CHUNK_SIZE = 100;

const config = {
  attendees: parseNonNegativeInteger(process.env.ATTENDEES, 1000),
  staff: parseNonNegativeInteger(process.env.STAFF, 100),
  sponsors: parseNonNegativeInteger(process.env.SPONSORS, 20),
  communities: parseNonNegativeInteger(process.env.COMMUNITIES, 20),
  userPrefix: process.env.FIXTURE_USER_PREFIX || "k6_user",
  tagPrefix: process.env.FIXTURE_TAG_PREFIX || "04:A6",
};

const users = [
  ...generateUsers("ATTENDEE", config.attendees),
  ...generateUsers("STAFF", config.staff),
  ...generateUsers("SPONSOR", config.sponsors),
  ...generateUsers("COMMUNITY", config.communities),
];
const tags = users.map((user, index) => ({
  physical_id: formatPhysicalId(index + 1),
  user_id: user.user_id,
}));

mkdirSync(outputDir, { recursive: true });
writeFileSync(
  join(outputDir, "full.json"),
  `${JSON.stringify(
    {
      generated_at: generatedAt,
      config,
      counts: {
        users: users.length,
        attendees: config.attendees,
        staff: config.staff,
        sponsors: config.sponsors,
        communities: config.communities,
        tags: tags.length,
      },
      users,
      tags,
    },
    null,
    2,
  )}\n`,
);
writeFileSync(join(outputDir, "seed-full.sql"), generateSeedSql());

console.log(`Generated ${users.length} users and ${tags.length} tag IDs in ${outputDir}`);

function generateUsers(role, count) {
  return Array.from({ length: count }, (_, index) => {
    const sequence = index + 1;
    const roleSlug = role.toLowerCase();
    const userId = `${config.userPrefix}_${roleSlug}_${String(sequence).padStart(4, "0")}`;

    return {
      user_id: userId,
      display_name: `${role}_${String(sequence).padStart(4, "0")}`,
      role,
      emoji_icon: emojiForRole(role),
      bio: `Deterministic k6 ${role.toLowerCase()} fixture user ${sequence}.`,
      pixel_avatar_base64: "",
      profile_version: 1,
      collection_version: 0,
    };
  });
}

function formatPhysicalId(sequence) {
  const hex = sequence.toString(16).toUpperCase().padStart(10, "0");
  const pairs = hex.match(/.{1,2}/g) ?? [];
  return [config.tagPrefix, ...pairs].join(":");
}

function generateSeedSql() {
  const lines = [
    "-- Deterministic k6 fixture data. Generated by scripts/k6/generate-fixture.mjs.",
    "PRAGMA foreign_keys = ON;",
    `DELETE FROM users WHERE user_id LIKE '${escapeSqlLike(config.userPrefix)}\\_%' ESCAPE '\\';`,
    "",
  ];

  for (let offset = 0; offset < users.length; offset += SQL_INSERT_CHUNK_SIZE) {
    const chunk = users.slice(offset, offset + SQL_INSERT_CHUNK_SIZE);
    lines.push(...generateUserInsertLines(chunk), "");
  }

  lines.push("");
  return lines.join("\n");
}

function generateUserInsertLines(chunk) {
  const lines = [
    "INSERT INTO users (",
    "  user_id,",
    "  display_name,",
    "  role,",
    "  emoji_icon,",
    "  bio,",
    "  pixel_avatar_base64,",
    "  profile_version,",
    "  collection_version,",
    "  created_at,",
    "  updated_at",
    ") VALUES",
  ];

  chunk.forEach((user, index) => {
    const suffix = index === chunk.length - 1 ? ";" : ",";
    lines.push(
      `  (${sqlString(user.user_id)}, ${sqlString(user.display_name)}, ${sqlString(
        user.role,
      )}, ${sqlString(user.emoji_icon)}, ${sqlString(user.bio)}, ${sqlString(
        user.pixel_avatar_base64,
      )}, ${user.profile_version}, ${user.collection_version}, ${sqlString(
        generatedAt,
      )}, ${sqlString(generatedAt)})${suffix}`,
    );
  });

  return lines;
}

function emojiForRole(role) {
  switch (role) {
    case "STAFF":
      return "💻";
    case "SPONSOR":
      return "🏢";
    case "COMMUNITY":
      return "🌱";
    default:
      return "🙂";
  }
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function escapeSqlLike(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/%/g, "\\%")
    .replace(/_/g, "\\_")
    .replace(/'/g, "''");
}

function parseNonNegativeInteger(value, fallback) {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed >= 0 ? parsed : fallback;
}
