export type UserRole = "ATTENDEE" | "STAFF" | "SPONSOR" | "COMMUNITY";

export type ErrorCode =
  | "BAD_REQUEST"
  | "UNAUTHORIZED"
  | "STAFF_DANGER_TOKEN_INVALID"
  | "FORBIDDEN"
  | "USER_NOT_FOUND"
  | "PHYSICAL_ID_MISMATCH"
  | "TAG_ALREADY_PAIRED"
  | "SCOREBOARD_ALREADY_FROZEN"
  | "SCOREBOARD_FREEZING"
  | "SCOREBOARD_NOT_FROZEN"
  | "SCOREBOARD_READ_INCONSISTENT"
  | "EVENT_ENDED"
  | "PRINT_CARD_NOT_FOUND"
  | "PAYLOAD_TOO_LARGE"
  | "RATE_LIMITED"
  | "PRIZE_NOT_ELIGIBLE"
  | "PRIZE_ALREADY_CLAIMED";

export interface AuthenticatedUser {
  userId: string;
  role: UserRole;
  issuer: string;
  audience: string;
  expiresAt: number;
}

export interface JwtPayload {
  sub: string;
  exp: number;
  iss: string;
  aud: string;
  role: UserRole;
}

export type EndpointRateLimitBinding =
  | "AUTH_HEALTH_RATE_LIMITER"
  | "MY_PROFILE_READ_RATE_LIMITER"
  | "MY_PROFILE_UPDATE_RATE_LIMITER"
  | "MY_PRIZE_READ_RATE_LIMITER"
  | "MY_BOOTSTRAP_RATE_LIMITER"
  | "USER_BATCH_READ_RATE_LIMITER"
  | "USER_PROFILE_READ_RATE_LIMITER"
  | "USER_COLLECTION_READ_RATE_LIMITER"
  | "TAG_PAIR_RATE_LIMITER"
  | "COLLECTION_SCAN_RATE_LIMITER"
  | "PHISHING_RECORD_RATE_LIMITER"
  | "STAMP_MISSION_READ_RATE_LIMITER"
  | "SCOREBOARD_READ_RATE_LIMITER"
  | "MY_SCOREBOARD_READ_RATE_LIMITER";

export interface AppBindings extends CloudflareBindings {
  PRINT_CARD_IMAGES?: R2Bucket;
  JWT_SECRET: string;
  STAFF_DANGER_TOKEN: string;
  AUTH_HEALTH_RATE_LIMITER: RateLimit;
  MY_PROFILE_READ_RATE_LIMITER: RateLimit;
  MY_PROFILE_UPDATE_RATE_LIMITER: RateLimit;
  MY_PRIZE_READ_RATE_LIMITER: RateLimit;
  MY_BOOTSTRAP_RATE_LIMITER: RateLimit;
  USER_BATCH_READ_RATE_LIMITER: RateLimit;
  USER_PROFILE_READ_RATE_LIMITER: RateLimit;
  USER_COLLECTION_READ_RATE_LIMITER: RateLimit;
  TAG_PAIR_RATE_LIMITER: RateLimit;
  COLLECTION_SCAN_RATE_LIMITER: RateLimit;
  PHISHING_RECORD_RATE_LIMITER: RateLimit;
  STAMP_MISSION_READ_RATE_LIMITER: RateLimit;
  SCOREBOARD_READ_RATE_LIMITER: RateLimit;
  MY_SCOREBOARD_READ_RATE_LIMITER: RateLimit;
  PRINT_CARD_USER_RATE_LIMITER: RateLimit;
  PRINT_CARD_GLOBAL_RATE_LIMITER: RateLimit;
}

export interface AppVariables {
  authUser: AuthenticatedUser;
}

export type AppEnv = {
  Bindings: AppBindings;
  Variables: AppVariables;
};
